#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
NOGGIN_HOME="${NOGGIN_HOME:-$HOME/.noggin}"
ENV_FILE="${NOGGIN_ENV:-$NOGGIN_HOME/noggin.env}"

PROVIDER=""
MODEL=""
BASE_URL=""
API_KEY=""
DB_PATH=""
GRAPH_DIR=""
SLACK_SECRET=""
GITHUB_TOKEN_VALUE=""
SYNC_TOKEN_VALUE=""
INSTALL_HERMES="no"
INSTALL_OPENCLAW="no"
RUN_LIVE_TEST="no"

main() {
  banner
  require_python
  create_venv
  configure_provider
  configure_storage
  configure_surfaces
  write_env_file
  install_agent_surfaces
  verify_install
  print_summary
}

banner() {
  cat <<'EOF'

Noggin setup
------------
This guided installer will:
  1. Create a local Python virtualenv.
  2. Install the noggin CLI.
  3. Configure your LLM provider.
  4. Create a Markdown knowledge graph directory.
  5. Connect optional surfaces such as Slack, GitHub, Hermes, and OpenClaw.

EOF
}

require_python() {
  if ! command -v python3 >/dev/null 2>&1; then
    echo "python3 is required." >&2
    exit 1
  fi
  python3 - <<'PY'
import sys
if sys.version_info < (3, 11):
    raise SystemExit("Noggin requires Python 3.11 or newer.")
PY
}

create_venv() {
  echo "Step 1: Python environment"
  if [[ ! -d "$ROOT/.venv" ]]; then
    echo "Creating .venv..."
    python3 -m venv "$ROOT/.venv"
  else
    echo "Using existing .venv."
  fi
  # shellcheck disable=SC1091
  source "$ROOT/.venv/bin/activate"
  python -m pip install --upgrade pip >/dev/null
  python -m pip install -e "$ROOT" >/dev/null
  echo "Installed noggin into $ROOT/.venv"
  echo
}

configure_provider() {
  echo "Step 2: LLM provider"
  cat <<'EOF'
Choose a provider:
  1. openai
  2. anthropic
  3. gemini
  4. openrouter
  5. groq
  6. together
  7. mistral
  8. ollama
  9. custom
EOF
  while true; do
    read -r -p "Provider [1]: " choice
    choice="${choice:-1}"
    case "$choice" in
      1|openai) PROVIDER="openai" ;;
      2|anthropic) PROVIDER="anthropic" ;;
      3|gemini) PROVIDER="gemini" ;;
      4|openrouter) PROVIDER="openrouter" ;;
      5|groq) PROVIDER="groq" ;;
      6|together) PROVIDER="together" ;;
      7|mistral) PROVIDER="mistral" ;;
      8|ollama) PROVIDER="ollama" ;;
      9|custom) PROVIDER="custom" ;;
      *) echo "Pick 1-9 or a provider name."; continue ;;
    esac
    break
  done

  default_provider_values "$PROVIDER"
  MODEL="$(prompt_default "Model" "$MODEL")"
  BASE_URL="$(prompt_default "Base URL" "$BASE_URL")"
  while [[ -z "$API_KEY" ]]; do
    read -r -s -p "API key/token for $PROVIDER: " API_KEY
    echo
    if [[ -z "$API_KEY" ]]; then
      echo "Noggin is LLM-only, so an API key/token is required."
    fi
  done
  echo
}

default_provider_values() {
  case "$1" in
    openai) MODEL="gpt-4o-mini"; BASE_URL="https://api.openai.com/v1" ;;
    anthropic) MODEL="claude-3-5-haiku-latest"; BASE_URL="https://api.anthropic.com/v1" ;;
    gemini) MODEL="gemini-1.5-flash"; BASE_URL="https://generativelanguage.googleapis.com/v1beta" ;;
    openrouter) MODEL="openai/gpt-4o-mini"; BASE_URL="https://openrouter.ai/api/v1" ;;
    groq) MODEL="llama-3.1-8b-instant"; BASE_URL="https://api.groq.com/openai/v1" ;;
    together) MODEL="meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo"; BASE_URL="https://api.together.xyz/v1" ;;
    mistral) MODEL="mistral-small-latest"; BASE_URL="https://api.mistral.ai/v1" ;;
    ollama) MODEL="llama3.1"; BASE_URL="http://127.0.0.1:11434/v1" ;;
    custom) MODEL="model"; BASE_URL="http://127.0.0.1:8000/v1" ;;
  esac
}

configure_storage() {
  echo "Step 3: Storage"
  DB_PATH="$(prompt_default "SQLite brain path" "$NOGGIN_HOME/brain.db")"
  GRAPH_DIR="$(prompt_default "Markdown graph directory" "$NOGGIN_HOME/graph")"
  echo
}

configure_surfaces() {
  echo "Step 4: Surfaces"
  if confirm "Configure Slack slash command secrets now?" "n"; then
    read -r -s -p "Slack signing secret: " SLACK_SECRET
    echo
  fi

  if confirm "Store a GitHub token for issue/PR ingestion?" "n"; then
    read -r -s -p "GitHub token: " GITHUB_TOKEN_VALUE
    echo
  fi

  if confirm "Create a token for Noggin peer sync?" "n"; then
    SYNC_TOKEN_VALUE="$(make_token)"
    echo "Generated NOGGIN_SYNC_TOKEN."
  fi

  if confirm "Install the Hermes skill/plugin files?" "n"; then
    INSTALL_HERMES="yes"
  fi

  if confirm "Install the OpenClaw skill file?" "n"; then
    INSTALL_OPENCLAW="yes"
  fi

  if confirm "Run a live LLM ingest/recall test after setup?" "n"; then
    RUN_LIVE_TEST="yes"
  fi
  echo
}

write_env_file() {
  echo "Step 5: Writing config"
  mkdir -p "$(dirname "$ENV_FILE")"
  umask 077
  tmp="$(mktemp "${ENV_FILE}.XXXXXX")"
  {
    echo "# Generated by Noggin setup."
    echo "# Noggin auto-loads this file. Keep it private."
    write_env_line "NOGGIN_PROVIDER" "$PROVIDER"
    write_env_line "NOGGIN_API_KEY" "$API_KEY"
    write_env_line "NOGGIN_MODEL" "$MODEL"
    write_env_line "NOGGIN_BASE_URL" "$BASE_URL"
    write_env_line "NOGGIN_DB" "$DB_PATH"
    write_env_line "NOGGIN_GRAPH_DIR" "$GRAPH_DIR"
    if [[ -n "$SLACK_SECRET" ]]; then
      write_env_line "NOGGIN_SLACK_SIGNING_SECRET" "$SLACK_SECRET"
    fi
    if [[ -n "$GITHUB_TOKEN_VALUE" ]]; then
      write_env_line "GITHUB_TOKEN" "$GITHUB_TOKEN_VALUE"
    fi
    if [[ -n "$SYNC_TOKEN_VALUE" ]]; then
      write_env_line "NOGGIN_SYNC_TOKEN" "$SYNC_TOKEN_VALUE"
    fi
  } > "$tmp"
  chmod 600 "$tmp"
  mv "$tmp" "$ENV_FILE"
  echo "Wrote $ENV_FILE"
  echo
}

install_agent_surfaces() {
  echo "Step 6: Agent surfaces"
  if [[ "$INSTALL_HERMES" == "yes" ]]; then
    "$ROOT/scripts/install-hermes.sh"
  fi
  if [[ "$INSTALL_OPENCLAW" == "yes" ]]; then
    "$ROOT/scripts/install-openclaw.sh"
  fi
  if [[ "$INSTALL_HERMES" != "yes" && "$INSTALL_OPENCLAW" != "yes" ]]; then
    echo "Skipped agent skill installation."
  fi
  echo
}

verify_install() {
  echo "Step 7: Verification"
  # shellcheck disable=SC1091
  source "$ROOT/.venv/bin/activate"
  NOGGIN_ENV="$ENV_FILE" noggin doctor

  if [[ "$RUN_LIVE_TEST" == "yes" ]]; then
    NOGGIN_ENV="$ENV_FILE" noggin ingest \
      --source setup --kind decision \
      "Decision: Noggin setup verified live LLM ingest." >/dev/null
    NOGGIN_ENV="$ENV_FILE" noggin recall "setup verified live LLM ingest"
  fi
  echo
}

print_summary() {
  cat <<EOF
Setup complete.

Config:
  $ENV_FILE

Noggin auto-loads that config file. To use this shell's venv directly:
  source "$ROOT/.venv/bin/activate"

Useful commands:
  noggin doctor
  noggin ingest "Decision: ..."
  noggin recall "..."
  noggin graph sync
  noggin mcp
  noggin dashboard --open
EOF

  if [[ -n "$SLACK_SECRET" ]]; then
    cat <<'EOF'

Slack:
  noggin slack serve --port 8787
  Configure your Slack slash command request URL to POST to /slack/command.
EOF
  fi

  if [[ -n "$SYNC_TOKEN_VALUE" ]]; then
    cat <<'EOF'

Peer sync:
  noggin sync serve --host 0.0.0.0 --port 8797
EOF
  fi
}

prompt_default() {
  local label="$1"
  local default="$2"
  local value
  read -r -p "$label [$default]: " value
  printf '%s' "${value:-$default}"
}

confirm() {
  local prompt="$1"
  local default="$2"
  local suffix="[y/N]"
  local answer
  if [[ "$default" == "y" ]]; then
    suffix="[Y/n]"
  fi
  while true; do
    read -r -p "$prompt $suffix " answer
    answer="${answer:-$default}"
    case "$answer" in
      y|Y|yes|YES) return 0 ;;
      n|N|no|NO) return 1 ;;
      *) echo "Answer y or n." ;;
    esac
  done
}

write_env_line() {
  printf '%s=%s\n' "$1" "$(shell_quote "$2")"
}

shell_quote() {
  local value="${1:-}"
  printf "'"
  printf '%s' "$value" | sed "s/'/'\\\\''/g"
  printf "'"
}

make_token() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 24
    return
  fi
  python3 - <<'PY'
import secrets
print(secrets.token_hex(24))
PY
}

main "$@"
